
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `snowIRT`=list(
        `type`="software", 
        `author`="Seol, H.", 
        `year`=2020, 
        `title`="snowIRT", 
        `publisher`="[jamovi module]. Retrieved from https://github.com/hyunsooseol/Rasch/", 
        `url`="https://github.com/hyunsooseol/Rasch"), 
    `TAM`=list(
        `type`="software", 
        `author`="Alexander Robitzsch and Thomas Kiefer and Margaret Wu", 
        `year`=2020, 
        `title`="TAM: Test Analysis Modules", 
        `publisher`="[R package]. Retrieved from https://CRAN.R-project.org/package=TAM", 
        `url`="https://CRAN.R-project.org/package=TAM"))
