
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `snowIRT`=list(
        `type`="software", 
        `author`="Seol, H.", 
        `year`=2020, 
        `title`="snowIRT: Item Response Theory for jamovi", 
        `publisher`="[jamovi module]. Retrieved from https://github.com/hyunsooseol/snowIRT"), 
    `TAM`=list(
        `type`="software", 
        `author`="Robitzsch,A., Kiefer, T., & Wu, M.", 
        `year`=2020, 
        `title`="TAM: Test Analysis Modules", 
        `publisher`="[R package]. Retrieved from https://CRAN.R-project.org/package=TAM"), 
    `difR`=list(
        `type`="software", 
        `author`="Magis, D., Beland, S., Tuerlincks, F., & De Boeck, P.", 
        `year`=2010, 
        `title`="difR: A general framework and an R package for the detection of dichotomous differential item functioning", 
        `publisher`="[R package]. Retrieved from https://CRAN.R-project.org/package=difR"), 
    `ShinyItemAnalysis`=list(
        `type`="software", 
        `author`="Martinkova, P., & Drabinova, A.", 
        `year`=2018, 
        `title`="ShinyItemAnalysis: for teaching psychometrics and to enforce routine analysis of educational tests", 
        `publisher`="[R package]. Retrieved from https://CRAN.R-project.org/package=ShinyItemAnalysis"), 
    `WrightMap`=list(
        `type`="software", 
        `author`="Irribarra, T., & Freund, R.", 
        `year`=2020, 
        `title`="Wright Map: IRT item-person map with ConQuest integration", 
        `publisher`="[R package]. Retrieved from https://CRAN.R-project.org/package=WrightMap"))
