
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `snowIRT`=list(
        `type`="software", 
        `author`="Seol, H.", 
        `year`=2020, 
        `title`="snowIRT: Rasch Measurement Model for jamovi", 
        `publisher`="[jamovi module]. Retrieved from https://github.com/hyunsooseol/snowIRT/", 
        `url`="https://github.com/hyunsooseol/snowIRT"), 
    `TAM`=list(
        `type`="software", 
        `author`="Alexander Robitzsch and Thomas Kiefer and Margaret Wu", 
        `year`=2020, 
        `title`="TAM: Test Analysis Modules", 
        `publisher`="[R package]. Retrieved from https://CRAN.R-project.org/package=TAM", 
        `url`="https://CRAN.R-project.org/package=TAM"), 
    `difR`=list(
        `type`="software", 
        `author`="D. Magis, S. Beland, F. Tuerlinckx, P. De Boeck", 
        `year`=2010, 
        `title`="difR: A general framework and an R package for the detection of dichotomous differential item functioning", 
        `publisher`="[R package]. Retrieved from https://CRAN.R-project.org/package=difR", 
        `url`="https://CRAN.R-project.org/package=difR"))
