
# This file is automatically generated, you probably don't want to edit this

clrOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "clrOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            group = NULL,
            model = NULL,
            clr = TRUE, ...) {

            super$initialize(
                package="snowIRT",
                name="clr",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..model <- jmvcore::OptionList$new(
                "model",
                model,
                options=list(
                    "RM",
                    "PCM"))
            private$..clr <- jmvcore::OptionBool$new(
                "clr",
                clr,
                default=TRUE)

            self$.addOption(private$..vars)
            self$.addOption(private$..group)
            self$.addOption(private$..model)
            self$.addOption(private$..clr)
        }),
    active = list(
        vars = function() private$..vars$value,
        group = function() private$..group$value,
        model = function() private$..model$value,
        clr = function() private$..clr$value),
    private = list(
        ..vars = NA,
        ..group = NA,
        ..model = NA,
        ..clr = NA)
)

clrResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "clrResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        text = function() private$.items[["text"]],
        clr = function() private$.items[["clr"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Conditional Likelihood Ratio Test")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Conditional Likelihood Ratio Test"))
            self$add(jmvcore::Table$new(
                options=options,
                name="clr",
                title="Conditional Likelihood Ratio Test",
                visible="(clr)",
                clearWith=list(
                    "vars",
                    "model"),
                refs="iarm",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="clr", 
                        `title`="CLR", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))}))

clrBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "clrBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowIRT",
                name = "clr",
                version = c(1,0,0),
                options = options,
                results = clrResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Conditional Likelihood Ratio Test
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param group A string naming the grouping variable from \code{data}
#' @param model .
#' @param clr .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$clr} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$clr$asDF}
#'
#' \code{as.data.frame(results$clr)}
#'
#' @export
clr <- function(
    data,
    vars,
    group,
    model,
    clr = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("clr requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- clrOptions$new(
        vars = vars,
        group = group,
        model = model,
        clr = clr)

    analysis <- clrClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

