
# This file is automatically generated, you probably don't want to edit this

clrOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "clrOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            group = NULL,
            model = NULL,
            num = 1,
            method = NULL,
            clr = TRUE,
            resi = FALSE,
            score = NULL,
            dif = FALSE,
            plot = FALSE,
            plot1 = FALSE, ...) {

            super$initialize(
                package="snowIRT",
                name="clr",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..model <- jmvcore::OptionList$new(
                "model",
                model,
                options=list(
                    "RM",
                    "PCM"))
            private$..num <- jmvcore::OptionInteger$new(
                "num",
                num,
                default=1,
                min=1)
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "score",
                    "cut"))
            private$..clr <- jmvcore::OptionBool$new(
                "clr",
                clr,
                default=TRUE)
            private$..resi <- jmvcore::OptionBool$new(
                "resi",
                resi,
                default=FALSE)
            private$..score <- jmvcore::OptionList$new(
                "score",
                score,
                options=list(
                    "low",
                    "high"))
            private$..dif <- jmvcore::OptionBool$new(
                "dif",
                dif,
                default=FALSE)
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=FALSE)
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..group)
            self$.addOption(private$..model)
            self$.addOption(private$..num)
            self$.addOption(private$..method)
            self$.addOption(private$..clr)
            self$.addOption(private$..resi)
            self$.addOption(private$..score)
            self$.addOption(private$..dif)
            self$.addOption(private$..plot)
            self$.addOption(private$..plot1)
        }),
    active = list(
        vars = function() private$..vars$value,
        group = function() private$..group$value,
        model = function() private$..model$value,
        num = function() private$..num$value,
        method = function() private$..method$value,
        clr = function() private$..clr$value,
        resi = function() private$..resi$value,
        score = function() private$..score$value,
        dif = function() private$..dif$value,
        plot = function() private$..plot$value,
        plot1 = function() private$..plot1$value),
    private = list(
        ..vars = NA,
        ..group = NA,
        ..model = NA,
        ..num = NA,
        ..method = NA,
        ..clr = NA,
        ..resi = NA,
        ..score = NA,
        ..dif = NA,
        ..plot = NA,
        ..plot1 = NA)
)

clrResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "clrResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        clr = function() private$.items[["clr"]],
        resi = function() private$.items[["resi"]],
        dif = function() private$.items[["dif"]],
        plot = function() private$.items[["plot"]],
        plot1 = function() private$.items[["plot1"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Conditional Likelihood Ratio Test",
                refs="snowIRT")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="clr",
                title="Conditional Likelihood Ratio Test",
                visible="(clr)",
                clearWith=list(
                    "vars",
                    "group",
                    "model"),
                refs="iarm",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="clr", 
                        `title`="Value", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="resi",
                title="`Standardized residuals - ${score}`",
                rows="(vars)",
                visible="(resi)",
                clearWith=list(
                    "vars",
                    "group",
                    "model",
                    "score"),
                refs="iarm",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="obs", 
                        `title`="Observed", 
                        `type`="number"),
                    list(
                        `name`="exp", 
                        `title`="Expexted", 
                        `type`="number"),
                    list(
                        `name`="std", 
                        `title`="Std.residuals", 
                        `type`="number"),
                    list(
                        `name`="sig", 
                        `title`="Sig.", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="dif",
                title="Partial Gamma Coefficients for DIF",
                visible="(dif)",
                rows="(vars)",
                clearWith=list(
                    "vars",
                    "group",
                    "model",
                    "padjust"),
                refs="iarm",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="gamma", 
                        `title`="Estimate", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="lower", 
                        `title`="Lower", 
                        `type`="number", 
                        `superTitle`="95% CI"),
                    list(
                        `name`="upper", 
                        `title`="Upper", 
                        `type`="number", 
                        `superTitle`="95% CI"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Item Characteristic Curve(ICC)",
                visible="(plot)",
                width=600,
                height=500,
                renderFun=".plot",
                refs="iarm",
                clearWith=list(
                    "vars",
                    "group",
                    "model",
                    "num")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Item Characteristic Curve for DIF",
                visible="(plot1)",
                width=600,
                height=500,
                renderFun=".plot1",
                refs="iarm",
                clearWith=list(
                    "vars",
                    "group",
                    "model",
                    "num",
                    "method")))}))

clrBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "clrBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowIRT",
                name = "clr",
                version = c(1,0,0),
                options = options,
                results = clrResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Conditional Likelihood Ratio Test
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param group A string naming the grouping variable from \code{data}
#' @param model .
#' @param num .
#' @param method .
#' @param clr .
#' @param resi .
#' @param score .
#' @param dif .
#' @param plot .
#' @param plot1 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$clr} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$resi} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$dif} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$clr$asDF}
#'
#' \code{as.data.frame(results$clr)}
#'
#' @export
clr <- function(
    data,
    vars,
    group,
    model,
    num = 1,
    method,
    clr = TRUE,
    resi = FALSE,
    score,
    dif = FALSE,
    plot = FALSE,
    plot1 = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("clr requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- clrOptions$new(
        vars = vars,
        group = group,
        model = model,
        num = num,
        method = method,
        clr = clr,
        resi = resi,
        score = score,
        dif = dif,
        plot = plot,
        plot1 = plot1)

    analysis <- clrClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

