
# This file is automatically generated, you probably don't want to edit this

deltamOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "deltamOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            group = NULL,
            fixed = TRUE,
            normal = FALSE,
            puri = NULL, ...) {

            super$initialize(
                package="snowIRT",
                name="deltam",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..fixed <- jmvcore::OptionBool$new(
                "fixed",
                fixed,
                default=TRUE)
            private$..normal <- jmvcore::OptionBool$new(
                "normal",
                normal,
                default=FALSE)
            private$..puri <- jmvcore::OptionList$new(
                "puri",
                puri,
                options=list(
                    "ip1",
                    "ip2",
                    "ip3"))

            self$.addOption(private$..vars)
            self$.addOption(private$..group)
            self$.addOption(private$..fixed)
            self$.addOption(private$..normal)
            self$.addOption(private$..puri)
        }),
    active = list(
        vars = function() private$..vars$value,
        group = function() private$..group$value,
        fixed = function() private$..fixed$value,
        normal = function() private$..normal$value,
        puri = function() private$..puri$value),
    private = list(
        ..vars = NA,
        ..group = NA,
        ..fixed = NA,
        ..normal = NA,
        ..puri = NA)
)

deltamResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "deltamResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        fixed = function() private$.items[["fixed"]],
        normal = function() private$.items[["normal"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Delta method")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="fixed",
                title="Delta method(Fixed)",
                visible="(fixed)",
                rows="(vars)",
                clearWith=list(
                    "vars"),
                refs="ShinyItemAnalysis",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="Item", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="pr", 
                        `title`="Prop.Reference"),
                    list(
                        `name`="pf", 
                        `title`="Prop.Focal"),
                    list(
                        `name`="dr", 
                        `title`="Delta.Reference"),
                    list(
                        `name`="df", 
                        `title`="Delta.Focal"),
                    list(
                        `name`="dist", 
                        `title`="Distance"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="normal",
                title="Iteration(Normal)",
                visible="(normal)",
                rows="(vars)",
                clearWith=list(
                    "vars"),
                refs="ShinyItemAnalysis",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="iter", 
                        `title`="1", 
                        `type`="number"))))}))

deltamBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "deltamBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowIRT",
                name = "deltam",
                version = c(1,0,0),
                options = options,
                results = deltamResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Delta method
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param group A string naming the grouping variable from \code{data}
#' @param fixed .
#' @param normal .
#' @param puri .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$fixed} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$normal} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$fixed$asDF}
#'
#' \code{as.data.frame(results$fixed)}
#'
#' @export
deltam <- function(
    data,
    vars,
    group,
    fixed = TRUE,
    normal = FALSE,
    puri) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("deltam requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(group), group, NULL))


    options <- deltamOptions$new(
        vars = vars,
        group = group,
        fixed = fixed,
        normal = normal,
        puri = puri)

    analysis <- deltamClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

