
# This file is automatically generated, you probably don't want to edit this

dichotomousOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "dichotomousOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            prop = TRUE,
            imeasure = FALSE,
            ise = FALSE,
            infit = FALSE,
            outfit = FALSE,
            reliability = TRUE,
            modelfit = FALSE,
            modelfitp = FALSE,
            mat = FALSE,
            wrightmap = FALSE,
            esc = FALSE, ...) {

            super$initialize(
                package='snowIRT',
                name='dichotomous',
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..prop <- jmvcore::OptionBool$new(
                "prop",
                prop,
                default=TRUE)
            private$..imeasure <- jmvcore::OptionBool$new(
                "imeasure",
                imeasure,
                default=FALSE)
            private$..ise <- jmvcore::OptionBool$new(
                "ise",
                ise,
                default=FALSE)
            private$..infit <- jmvcore::OptionBool$new(
                "infit",
                infit,
                default=FALSE)
            private$..outfit <- jmvcore::OptionBool$new(
                "outfit",
                outfit,
                default=FALSE)
            private$..reliability <- jmvcore::OptionBool$new(
                "reliability",
                reliability,
                default=TRUE)
            private$..modelfit <- jmvcore::OptionBool$new(
                "modelfit",
                modelfit,
                default=FALSE)
            private$..modelfitp <- jmvcore::OptionBool$new(
                "modelfitp",
                modelfitp,
                default=FALSE)
            private$..mat <- jmvcore::OptionBool$new(
                "mat",
                mat,
                default=FALSE)
            private$..wrightmap <- jmvcore::OptionBool$new(
                "wrightmap",
                wrightmap,
                default=FALSE)
            private$..esc <- jmvcore::OptionBool$new(
                "esc",
                esc,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..prop)
            self$.addOption(private$..imeasure)
            self$.addOption(private$..ise)
            self$.addOption(private$..infit)
            self$.addOption(private$..outfit)
            self$.addOption(private$..reliability)
            self$.addOption(private$..modelfit)
            self$.addOption(private$..modelfitp)
            self$.addOption(private$..mat)
            self$.addOption(private$..wrightmap)
            self$.addOption(private$..esc)
        }),
    active = list(
        vars = function() private$..vars$value,
        prop = function() private$..prop$value,
        imeasure = function() private$..imeasure$value,
        ise = function() private$..ise$value,
        infit = function() private$..infit$value,
        outfit = function() private$..outfit$value,
        reliability = function() private$..reliability$value,
        modelfit = function() private$..modelfit$value,
        modelfitp = function() private$..modelfitp$value,
        mat = function() private$..mat$value,
        wrightmap = function() private$..wrightmap$value,
        esc = function() private$..esc$value),
    private = list(
        ..vars = NA,
        ..prop = NA,
        ..imeasure = NA,
        ..ise = NA,
        ..infit = NA,
        ..outfit = NA,
        ..reliability = NA,
        ..modelfit = NA,
        ..modelfitp = NA,
        ..mat = NA,
        ..wrightmap = NA,
        ..esc = NA)
)

dichotomousResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        scale = function() private$.items[["scale"]],
        mat = function() private$.items[["mat"]],
        items = function() private$.items[["items"]],
        plot = function() private$.items[["plot"]],
        esc = function() private$.items[["esc"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Dichotomous Rasch Model")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE,
                refs="snowIRT"))
            self$add(jmvcore::Table$new(
                options=options,
                name="scale",
                title="Model Fit",
                rows=1,
                clearWith=list(
                    "vars"),
                refs="TAM",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="scale"),
                    list(
                        `name`="reliability", 
                        `title`="Person Reliability", 
                        `visible`="(reliability)"),
                    list(
                        `name`="modelfit", 
                        `title`="MADaQ3", 
                        `visible`="(modelfit)"),
                    list(
                        `name`="modelfitp", 
                        `title`="p", 
                        `format`="zto,pvalue", 
                        `visible`="(modelfitp)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="mat",
                title="Q3 Correlation Matrix",
                rows="(vars)",
                visible="(mat)",
                refs="TAM",
                columns=list(
                    list(
                        `name`=".name[r]", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)", 
                        `combineBelow`=TRUE),
                    list(
                        `name`=".stat[r]", 
                        `title`="", 
                        `type`="text", 
                        `content`="r"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="items",
                title="Item Statistics",
                visible="(prop || imeasure || ise || infit || outfit)",
                rows="(vars)",
                clearWith=list(
                    "vars"),
                refs="TAM",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="prop", 
                        `title`="Proportion", 
                        `visible`="(prop)"),
                    list(
                        `name`="measure", 
                        `title`="Measure", 
                        `visible`="(imeasure)"),
                    list(
                        `name`="ise", 
                        `title`="S.E.Measure", 
                        `visible`="(ise)"),
                    list(
                        `name`="infit", 
                        `title`="Infit", 
                        `visible`="(infit)"),
                    list(
                        `name`="outfit", 
                        `title`="Outfit", 
                        `visible`="(outfit)"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Wright Map",
                width=500,
                height=500,
                renderFun=".plot",
                visible="(wrightmap)",
                refs="TAM"))
            self$add(jmvcore::Array$new(
                options=options,
                name="esc",
                title="Expected Score Curve",
                items="(vars)",
                template=jmvcore::Image$new(
                    options=options,
                    title="$key",
                    width=300,
                    height=300,
                    visible="(esc)",
                    renderFun=".escPlot",
                    clearWith=list())))}))

dichotomousBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "dichotomousBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'snowIRT',
                name = 'dichotomous',
                version = c(1,0,0),
                options = options,
                results = dichotomousResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Dichotomous Rasch Model
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param prop .
#' @param imeasure .
#' @param ise .
#' @param infit .
#' @param outfit .
#' @param reliability .
#' @param modelfit .
#' @param modelfitp .
#' @param mat .
#' @param wrightmap .
#' @param esc .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$scale} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$mat} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$items} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$esc} \tab \tab \tab \tab \tab an array of plots \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$scale$asDF}
#'
#' \code{as.data.frame(results$scale)}
#'
#' @export
dichotomous <- function(
    data,
    vars,
    prop = TRUE,
    imeasure = FALSE,
    ise = FALSE,
    infit = FALSE,
    outfit = FALSE,
    reliability = TRUE,
    modelfit = FALSE,
    modelfitp = FALSE,
    mat = FALSE,
    wrightmap = FALSE,
    esc = FALSE) {

    if ( ! requireNamespace('jmvcore'))
        stop('dichotomous requires jmvcore to be installed (restart may be required)')

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- dichotomousOptions$new(
        vars = vars,
        prop = prop,
        imeasure = imeasure,
        ise = ise,
        infit = infit,
        outfit = outfit,
        reliability = reliability,
        modelfit = modelfit,
        modelfitp = modelfitp,
        mat = mat,
        wrightmap = wrightmap,
        esc = esc)

    analysis <- dichotomousClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
