
# This file is automatically generated, you probably don't want to edit this

difOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "difOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            group = NULL,
            raju = TRUE,
            difplot = FALSE, ...) {

            super$initialize(
                package='snowIRT',
                name='dif',
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..raju <- jmvcore::OptionBool$new(
                "raju",
                raju,
                default=TRUE)
            private$..difplot <- jmvcore::OptionBool$new(
                "difplot",
                difplot,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..group)
            self$.addOption(private$..raju)
            self$.addOption(private$..difplot)
        }),
    active = list(
        vars = function() private$..vars$value,
        group = function() private$..group$value,
        raju = function() private$..raju$value,
        difplot = function() private$..difplot$value),
    private = list(
        ..vars = NA,
        ..group = NA,
        ..raju = NA,
        ..difplot = NA)
)

difResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        raju = function() private$.items[["raju"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Differential Item Functioning")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE,
                refs="snowIRT"))
            self$add(jmvcore::Table$new(
                options=options,
                name="raju",
                title="Raju\u2019s area method",
                visible="(raju)",
                rows="(vars)",
                clearWith=list(
                    "vars"),
                refs="difR",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="zstat", 
                        `title`="z"),
                    list(
                        `name`="pvalue", 
                        `title`="Adj.p", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="delta", 
                        `title`="deltaRaju"),
                    list(
                        `name`="es", 
                        `title`="Effect size", 
                        `type`="text"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="DIF plot",
                width=500,
                height=500,
                renderFun=".plot",
                visible="(difplot)",
                refs="difR"))}))

difBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "difBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'snowIRT',
                name = 'dif',
                version = c(1,0,0),
                options = options,
                results = difResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Differential Item Functioning
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param group A string naming the grouping variable from \code{data}
#' @param raju .
#' @param difplot .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$raju} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$raju$asDF}
#'
#' \code{as.data.frame(results$raju)}
#'
#' @export
dif <- function(
    data,
    vars,
    group,
    raju = TRUE,
    difplot = FALSE) {

    if ( ! requireNamespace('jmvcore'))
        stop('dif requires jmvcore to be installed (restart may be required)')

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(group), group, NULL))


    options <- difOptions$new(
        vars = vars,
        group = group,
        raju = raju,
        difplot = difplot)

    analysis <- difClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
