
# This file is automatically generated, you probably don't want to edit this

difOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "difOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            group = NULL,
            raju = TRUE,
            padjust = "BH",
            zplot = FALSE,
            iccplot = FALSE, ...) {

            super$initialize(
                package="snowIRT",
                name="dif",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..raju <- jmvcore::OptionBool$new(
                "raju",
                raju,
                default=TRUE)
            private$..padjust <- jmvcore::OptionList$new(
                "padjust",
                padjust,
                options=list(
                    "none",
                    "holm",
                    "hochberg",
                    "hommel",
                    "bonferroni",
                    "BH",
                    "BY",
                    "fdr"),
                default="BH")
            private$..zplot <- jmvcore::OptionBool$new(
                "zplot",
                zplot,
                default=FALSE)
            private$..iccplot <- jmvcore::OptionBool$new(
                "iccplot",
                iccplot,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..group)
            self$.addOption(private$..raju)
            self$.addOption(private$..padjust)
            self$.addOption(private$..zplot)
            self$.addOption(private$..iccplot)
        }),
    active = list(
        vars = function() private$..vars$value,
        group = function() private$..group$value,
        raju = function() private$..raju$value,
        padjust = function() private$..padjust$value,
        zplot = function() private$..zplot$value,
        iccplot = function() private$..iccplot$value),
    private = list(
        ..vars = NA,
        ..group = NA,
        ..raju = NA,
        ..padjust = NA,
        ..zplot = NA,
        ..iccplot = NA)
)

difResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "difResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        raju = function() private$.items[["raju"]],
        zplot = function() private$.items[["zplot"]],
        iccplot = function() private$.items[["iccplot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Differential Item Functioning",
                refs="snowIRT")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="raju",
                title="Raju\u2019s area method",
                visible="(raju)",
                rows="(vars)",
                clearWith=list(
                    "vars",
                    "padjust"),
                refs="difR",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="zstat", 
                        `title`="Statistic"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="padjust", 
                        `title`="Adj.p", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="delta", 
                        `title`="deltaRaju"),
                    list(
                        `name`="es", 
                        `title`="Effect size", 
                        `type`="text"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="zplot",
                title="Z statistic",
                width=500,
                height=500,
                renderFun=".plot",
                visible="(zplot)",
                refs="difR"))
            self$add(jmvcore::Array$new(
                options=options,
                name="iccplot",
                title="Item characteristic curve for DIF",
                items="(vars)",
                refs="ShinyItemAnalysis",
                template=jmvcore::Image$new(
                    options=options,
                    title="$key",
                    width=400,
                    height=400,
                    visible="(iccplot)",
                    renderFun=".iccplot",
                    clearWith=list())))}))

difBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "difBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowIRT",
                name = "dif",
                version = c(1,0,0),
                options = options,
                results = difResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Raju method
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param group A string naming the grouping variable from \code{data}
#' @param raju .
#' @param padjust .
#' @param zplot .
#' @param iccplot .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$raju} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$zplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$iccplot} \tab \tab \tab \tab \tab an array of plots \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$raju$asDF}
#'
#' \code{as.data.frame(results$raju)}
#'
#' @export
dif <- function(
    data,
    vars,
    group,
    raju = TRUE,
    padjust = "BH",
    zplot = FALSE,
    iccplot = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("dif requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(group), group, NULL))


    options <- difOptions$new(
        vars = vars,
        group = group,
        raju = raju,
        padjust = padjust,
        zplot = zplot,
        iccplot = iccplot)

    analysis <- difClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

