
# This file is automatically generated, you probably don't want to edit this

facetOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "facetOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            id = NULL,
            facet = NULL,
            fm = FALSE,
            ifit = FALSE, ...) {

            super$initialize(
                package="snowIRT",
                name="facet",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..id <- jmvcore::OptionVariable$new(
                "id",
                id)
            private$..facet <- jmvcore::OptionVariables$new(
                "facet",
                facet)
            private$..fm <- jmvcore::OptionBool$new(
                "fm",
                fm,
                default=FALSE)
            private$..ifit <- jmvcore::OptionBool$new(
                "ifit",
                ifit,
                default=FALSE)

            self$.addOption(private$..dep)
            self$.addOption(private$..id)
            self$.addOption(private$..facet)
            self$.addOption(private$..fm)
            self$.addOption(private$..ifit)
        }),
    active = list(
        dep = function() private$..dep$value,
        id = function() private$..id$value,
        facet = function() private$..facet$value,
        fm = function() private$..fm$value,
        ifit = function() private$..ifit$value),
    private = list(
        ..dep = NA,
        ..id = NA,
        ..facet = NA,
        ..fm = NA,
        ..ifit = NA)
)

facetResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "facetResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        text = function() private$.items[["text"]],
        fm = function() private$.items[["fm"]],
        ifit = function() private$.items[["ifit"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Facet Model")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Facet Model"))
            self$add(jmvcore::Table$new(
                options=options,
                name="fm",
                title="Facet measure",
                visible="(fm)",
                clearWith=list(
                    "dep",
                    "id",
                    "facet"),
                refs="TAM",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="measure", 
                        `title`="Measure", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="ifit",
                title="Item fit",
                visible="(ifit)",
                clearWith=list(
                    "dep",
                    "id",
                    "facet"),
                refs="TAM",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="outfit.t", 
                        `title`="Outfit_t", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `format`="zto,pvalue"))))}))

facetBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "facetBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowIRT",
                name = "facet",
                version = c(1,0,0),
                options = options,
                results = facetResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Facet Model
#'
#' 
#' @param data .
#' @param dep .
#' @param id .
#' @param facet .
#' @param fm .
#' @param ifit .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$fm} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ifit} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$fm$asDF}
#'
#' \code{as.data.frame(results$fm)}
#'
#' @export
facet <- function(
    data,
    dep,
    id,
    facet,
    fm = FALSE,
    ifit = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("facet requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(id)) id <- jmvcore::resolveQuo(jmvcore::enquo(id))
    if ( ! missing(facet)) facet <- jmvcore::resolveQuo(jmvcore::enquo(facet))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(id), id, NULL),
            `if`( ! missing(facet), facet, NULL))


    options <- facetOptions$new(
        dep = dep,
        id = id,
        facet = facet,
        fm = fm,
        ifit = ifit)

    analysis <- facetClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

