
# This file is automatically generated, you probably don't want to edit this

facetOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "facetOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            id = NULL,
            facet = NULL, ...) {

            super$initialize(
                package="snowIRT",
                name="facet",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..id <- jmvcore::OptionVariable$new(
                "id",
                id)
            private$..facet <- jmvcore::OptionVariables$new(
                "facet",
                facet)

            self$.addOption(private$..dep)
            self$.addOption(private$..id)
            self$.addOption(private$..facet)
        }),
    active = list(
        dep = function() private$..dep$value,
        id = function() private$..id$value,
        facet = function() private$..facet$value),
    private = list(
        ..dep = NA,
        ..id = NA,
        ..facet = NA)
)

facetResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "facetResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Facet Model")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Facet Model"))}))

facetBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "facetBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowIRT",
                name = "facet",
                version = c(1,0,0),
                options = options,
                results = facetResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Facet Model
#'
#' 
#' @param data .
#' @param dep .
#' @param id .
#' @param facet .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
facet <- function(
    data,
    dep,
    id,
    facet) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("facet requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(id)) id <- jmvcore::resolveQuo(jmvcore::enquo(id))
    if ( ! missing(facet)) facet <- jmvcore::resolveQuo(jmvcore::enquo(facet))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(id), id, NULL),
            `if`( ! missing(facet), facet, NULL))


    options <- facetOptions$new(
        dep = dep,
        id = id,
        facet = facet)

    analysis <- facetClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

