
# This file is automatically generated, you probably don't want to edit this

facetOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "facetOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            id = NULL,
            facet = NULL,
            rm = FALSE,
            im = FALSE,
            inter = FALSE,
            sm = FALSE,
            ifit = FALSE,
            pm = FALSE,
            pfit = FALSE,
            plot1 = FALSE,
            width1 = 500,
            height1 = 500,
            plot2 = FALSE,
            width2 = 500,
            height2 = 500,
            plot3 = FALSE,
            width3 = 500,
            height3 = 500,
            angle = 0, ...) {

            super$initialize(
                package="snowIRT",
                name="facet",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..id <- jmvcore::OptionVariable$new(
                "id",
                id,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..facet <- jmvcore::OptionVariables$new(
                "facet",
                facet,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..rm <- jmvcore::OptionBool$new(
                "rm",
                rm,
                default=FALSE)
            private$..im <- jmvcore::OptionBool$new(
                "im",
                im,
                default=FALSE)
            private$..inter <- jmvcore::OptionBool$new(
                "inter",
                inter,
                default=FALSE)
            private$..sm <- jmvcore::OptionBool$new(
                "sm",
                sm,
                default=FALSE)
            private$..ifit <- jmvcore::OptionBool$new(
                "ifit",
                ifit,
                default=FALSE)
            private$..pm <- jmvcore::OptionBool$new(
                "pm",
                pm,
                default=FALSE)
            private$..pfit <- jmvcore::OptionBool$new(
                "pfit",
                pfit,
                default=FALSE)
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=FALSE)
            private$..width1 <- jmvcore::OptionInteger$new(
                "width1",
                width1,
                default=500)
            private$..height1 <- jmvcore::OptionInteger$new(
                "height1",
                height1,
                default=500)
            private$..plot2 <- jmvcore::OptionBool$new(
                "plot2",
                plot2,
                default=FALSE)
            private$..width2 <- jmvcore::OptionInteger$new(
                "width2",
                width2,
                default=500)
            private$..height2 <- jmvcore::OptionInteger$new(
                "height2",
                height2,
                default=500)
            private$..plot3 <- jmvcore::OptionBool$new(
                "plot3",
                plot3,
                default=FALSE)
            private$..width3 <- jmvcore::OptionInteger$new(
                "width3",
                width3,
                default=500)
            private$..height3 <- jmvcore::OptionInteger$new(
                "height3",
                height3,
                default=500)
            private$..angle <- jmvcore::OptionNumber$new(
                "angle",
                angle,
                min=0,
                max=90,
                default=0)

            self$.addOption(private$..dep)
            self$.addOption(private$..id)
            self$.addOption(private$..facet)
            self$.addOption(private$..rm)
            self$.addOption(private$..im)
            self$.addOption(private$..inter)
            self$.addOption(private$..sm)
            self$.addOption(private$..ifit)
            self$.addOption(private$..pm)
            self$.addOption(private$..pfit)
            self$.addOption(private$..plot1)
            self$.addOption(private$..width1)
            self$.addOption(private$..height1)
            self$.addOption(private$..plot2)
            self$.addOption(private$..width2)
            self$.addOption(private$..height2)
            self$.addOption(private$..plot3)
            self$.addOption(private$..width3)
            self$.addOption(private$..height3)
            self$.addOption(private$..angle)
        }),
    active = list(
        dep = function() private$..dep$value,
        id = function() private$..id$value,
        facet = function() private$..facet$value,
        rm = function() private$..rm$value,
        im = function() private$..im$value,
        inter = function() private$..inter$value,
        sm = function() private$..sm$value,
        ifit = function() private$..ifit$value,
        pm = function() private$..pm$value,
        pfit = function() private$..pfit$value,
        plot1 = function() private$..plot1$value,
        width1 = function() private$..width1$value,
        height1 = function() private$..height1$value,
        plot2 = function() private$..plot2$value,
        width2 = function() private$..width2$value,
        height2 = function() private$..height2$value,
        plot3 = function() private$..plot3$value,
        width3 = function() private$..width3$value,
        height3 = function() private$..height3$value,
        angle = function() private$..angle$value),
    private = list(
        ..dep = NA,
        ..id = NA,
        ..facet = NA,
        ..rm = NA,
        ..im = NA,
        ..inter = NA,
        ..sm = NA,
        ..ifit = NA,
        ..pm = NA,
        ..pfit = NA,
        ..plot1 = NA,
        ..width1 = NA,
        ..height1 = NA,
        ..plot2 = NA,
        ..width2 = NA,
        ..height2 = NA,
        ..plot3 = NA,
        ..width3 = NA,
        ..height3 = NA,
        ..angle = NA)
)

facetResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "facetResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        text1 = function() private$.items[["text1"]],
        text = function() private$.items[["text"]],
        im = function() private$.items[["im"]],
        rm = function() private$.items[["rm"]],
        inter = function() private$.items[["inter"]],
        sm = function() private$.items[["sm"]],
        ifit = function() private$.items[["ifit"]],
        pm = function() private$.items[["pm"]],
        pfit = function() private$.items[["pfit"]],
        plot1 = function() private$.items[["plot1"]],
        plot2 = function() private$.items[["plot2"]],
        plot3 = function() private$.items[["plot3"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Many Facet Model")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text1",
                title=""))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="WLE Reliability"))
            self$add(jmvcore::Table$new(
                options=options,
                name="im",
                title="Task measure",
                visible="(im)",
                clearWith=list(
                    "dep",
                    "id",
                    "facet"),
                refs="TAM",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="measure", 
                        `title`="Measure", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="rm",
                title="Rater measure",
                visible="(rm)",
                clearWith=list(
                    "dep",
                    "id",
                    "facet"),
                refs="TAM",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="measure", 
                        `title`="Measure", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="inter",
                title="Rater X Task",
                visible="(inter)",
                clearWith=list(
                    "dep",
                    "id",
                    "facet"),
                refs="TAM",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="rater", 
                        `title`="Rater", 
                        `type`="text"),
                    list(
                        `name`="task", 
                        `title`="Task", 
                        `type`="text"),
                    list(
                        `name`="measure", 
                        `title`="Measure", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="sm",
                title="Step measure",
                visible="(sm)",
                clearWith=list(
                    "dep",
                    "id",
                    "facet"),
                refs="TAM",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="measure", 
                        `title`="Measure", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="ifit",
                title="Interaction fit: Rater X Task",
                visible="(ifit)",
                clearWith=list(
                    "dep",
                    "id",
                    "facet"),
                refs="TAM",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="rater", 
                        `title`="Rater", 
                        `type`="text"),
                    list(
                        `name`="task", 
                        `title`="Task", 
                        `type`="text"),
                    list(
                        `name`="outfit", 
                        `title`="Outfit_t", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="pm",
                title="Person measure",
                visible="(pm)",
                clearWith=list(
                    "dep",
                    "id",
                    "facet"),
                refs="TAM",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="ps", 
                        `title`="Score", 
                        `type`="integer"),
                    list(
                        `name`="pt", 
                        `title`="Theta", 
                        `type`="number"),
                    list(
                        `name`="pe", 
                        `title`="SE", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="pfit",
                title="Person fit",
                visible="(pfit)",
                clearWith=list(
                    "dep",
                    "id",
                    "facet"),
                refs="TAM",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="outfit", 
                        `title`="Outfit", 
                        `type`="number"),
                    list(
                        `name`="infit", 
                        `title`="Infit", 
                        `format`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Rater plot",
                visible="(plot1)",
                renderFun=".plot1",
                refs="snowIRT",
                clearWith=list(
                    "dep",
                    "id",
                    "facet",
                    "width1",
                    "height1")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot2",
                title="Task plot",
                visible="(plot2)",
                renderFun=".plot2",
                refs="snowIRT",
                clearWith=list(
                    "dep",
                    "id",
                    "facet",
                    "width2",
                    "height2")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot3",
                title="Rater X Task plot",
                visible="(plot3)",
                renderFun=".plot3",
                refs="snowIRT",
                clearWith=list(
                    "dep",
                    "id",
                    "facet",
                    "width3",
                    "height3",
                    "angle")))}))

facetBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "facetBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowIRT",
                name = "facet",
                version = c(1,0,0),
                options = options,
                results = facetResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Many Facet Model
#'
#' 
#' @param data .
#' @param dep .
#' @param id .
#' @param facet .
#' @param rm .
#' @param im .
#' @param inter .
#' @param sm .
#' @param ifit .
#' @param pm .
#' @param pfit .
#' @param plot1 .
#' @param width1 .
#' @param height1 .
#' @param plot2 .
#' @param width2 .
#' @param height2 .
#' @param plot3 .
#' @param width3 .
#' @param height3 .
#' @param angle .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text1} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$im} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$rm} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$inter} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$sm} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ifit} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$pm} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$pfit} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot2} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot3} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$im$asDF}
#'
#' \code{as.data.frame(results$im)}
#'
#' @export
facet <- function(
    data,
    dep,
    id,
    facet,
    rm = FALSE,
    im = FALSE,
    inter = FALSE,
    sm = FALSE,
    ifit = FALSE,
    pm = FALSE,
    pfit = FALSE,
    plot1 = FALSE,
    width1 = 500,
    height1 = 500,
    plot2 = FALSE,
    width2 = 500,
    height2 = 500,
    plot3 = FALSE,
    width3 = 500,
    height3 = 500,
    angle = 0) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("facet requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(id)) id <- jmvcore::resolveQuo(jmvcore::enquo(id))
    if ( ! missing(facet)) facet <- jmvcore::resolveQuo(jmvcore::enquo(facet))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(id), id, NULL),
            `if`( ! missing(facet), facet, NULL))

    for (v in id) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in facet) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- facetOptions$new(
        dep = dep,
        id = id,
        facet = facet,
        rm = rm,
        im = im,
        inter = inter,
        sm = sm,
        ifit = ifit,
        pm = pm,
        pfit = pfit,
        plot1 = plot1,
        width1 = width1,
        height1 = height1,
        plot2 = plot2,
        width2 = width2,
        height2 = height2,
        plot3 = plot3,
        width3 = width3,
        height3 = height3,
        angle = angle)

    analysis <- facetClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

