
# This file is automatically generated, you probably don't want to edit this

itemOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "itemOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            key = "D,C,A,D,D,A,D,B,D,A,A,D,C,C,B,C,D,A,A,B",
            num = 1,
            count = TRUE,
            prop = FALSE,
            plot = FALSE, ...) {

            super$initialize(
                package="snowIRT",
                name="item",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..key <- jmvcore::OptionString$new(
                "key",
                key,
                default="D,C,A,D,D,A,D,B,D,A,A,D,C,C,B,C,D,A,A,B")
            private$..num <- jmvcore::OptionInteger$new(
                "num",
                num,
                default=1,
                min=1)
            private$..count <- jmvcore::OptionBool$new(
                "count",
                count,
                default=TRUE)
            private$..prop <- jmvcore::OptionBool$new(
                "prop",
                prop,
                default=FALSE)
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..key)
            self$.addOption(private$..num)
            self$.addOption(private$..count)
            self$.addOption(private$..prop)
            self$.addOption(private$..plot)
        }),
    active = list(
        vars = function() private$..vars$value,
        key = function() private$..key$value,
        num = function() private$..num$value,
        count = function() private$..count$value,
        prop = function() private$..prop$value,
        plot = function() private$..plot$value),
    private = list(
        ..vars = NA,
        ..key = NA,
        ..num = NA,
        ..count = NA,
        ..prop = NA,
        ..plot = NA)
)

itemResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "itemResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        count = function() private$.items[["count"]],
        prop = function() private$.items[["prop"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Distractor analysis")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="count",
                title="Counts of respondents",
                visible="(count)"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="prop",
                title="Proportions of respondents",
                visible="(prop)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Distractor plot",
                requiresData=TRUE,
                visible="(plot)",
                width=400,
                height=400,
                renderFun=".plot",
                clearWith=list(
                    "vars",
                    "num")))}))

itemBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "itemBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowIRT",
                name = "item",
                version = c(1,0,0),
                options = options,
                results = itemResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Distractor analysis
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param key .
#' @param num .
#' @param count .
#' @param prop .
#' @param plot .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$count} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$prop} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
item <- function(
    data,
    vars,
    key = "D,C,A,D,D,A,D,B,D,A,A,D,C,C,B,C,D,A,A,B",
    num = 1,
    count = TRUE,
    prop = FALSE,
    plot = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("item requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))

    for (v in vars) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- itemOptions$new(
        vars = vars,
        key = key,
        num = num,
        count = count,
        prop = prop,
        plot = plot)

    analysis <- itemClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

