
# This file is automatically generated, you probably don't want to edit this

itemOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "itemOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            key = "D,C,A,D,D,A,D,B,D,A,A,D,C,C,B,C,D,A,A,B",
            num = 1,
            num1 = 1,
            group = 3,
            group1 = 3,
            count = TRUE,
            prop = FALSE,
            sum = FALSE,
            disc = FALSE,
            sum1 = FALSE,
            plot = FALSE,
            angle = 0,
            plot1 = FALSE,
            disi = NULL,
            plot2 = FALSE,
            plot3 = FALSE,
            width2 = 500,
            height2 = 500,
            width = 500,
            height = 500,
            width1 = 500,
            height1 = 500,
            width3 = 500,
            height3 = 500, ...) {

            super$initialize(
                package="snowIRT",
                name="item",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..key <- jmvcore::OptionString$new(
                "key",
                key,
                default="D,C,A,D,D,A,D,B,D,A,A,D,C,C,B,C,D,A,A,B")
            private$..num <- jmvcore::OptionInteger$new(
                "num",
                num,
                default=1,
                min=1)
            private$..num1 <- jmvcore::OptionInteger$new(
                "num1",
                num1,
                default=1,
                min=1)
            private$..group <- jmvcore::OptionInteger$new(
                "group",
                group,
                default=3,
                min=2)
            private$..group1 <- jmvcore::OptionInteger$new(
                "group1",
                group1,
                default=3,
                min=3)
            private$..count <- jmvcore::OptionBool$new(
                "count",
                count,
                default=TRUE)
            private$..prop <- jmvcore::OptionBool$new(
                "prop",
                prop,
                default=FALSE)
            private$..sum <- jmvcore::OptionBool$new(
                "sum",
                sum,
                default=FALSE)
            private$..disc <- jmvcore::OptionBool$new(
                "disc",
                disc,
                default=FALSE)
            private$..sum1 <- jmvcore::OptionBool$new(
                "sum1",
                sum1,
                default=FALSE)
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=FALSE)
            private$..angle <- jmvcore::OptionNumber$new(
                "angle",
                angle,
                min=0,
                max=90,
                default=0)
            private$..plot1 <- jmvcore::OptionBool$new(
                "plot1",
                plot1,
                default=FALSE)
            private$..disi <- jmvcore::OptionList$new(
                "disi",
                disi,
                options=list(
                    "ULI",
                    "RIT",
                    "RIR"))
            private$..plot2 <- jmvcore::OptionBool$new(
                "plot2",
                plot2,
                default=FALSE)
            private$..total <- jmvcore::OptionOutput$new(
                "total")
            private$..scoring <- jmvcore::OptionOutput$new(
                "scoring")
            private$..plot3 <- jmvcore::OptionBool$new(
                "plot3",
                plot3,
                default=FALSE)
            private$..width2 <- jmvcore::OptionInteger$new(
                "width2",
                width2,
                default=500)
            private$..height2 <- jmvcore::OptionInteger$new(
                "height2",
                height2,
                default=500)
            private$..width <- jmvcore::OptionInteger$new(
                "width",
                width,
                default=500)
            private$..height <- jmvcore::OptionInteger$new(
                "height",
                height,
                default=500)
            private$..width1 <- jmvcore::OptionInteger$new(
                "width1",
                width1,
                default=500)
            private$..height1 <- jmvcore::OptionInteger$new(
                "height1",
                height1,
                default=500)
            private$..width3 <- jmvcore::OptionInteger$new(
                "width3",
                width3,
                default=500)
            private$..height3 <- jmvcore::OptionInteger$new(
                "height3",
                height3,
                default=500)

            self$.addOption(private$..vars)
            self$.addOption(private$..key)
            self$.addOption(private$..num)
            self$.addOption(private$..num1)
            self$.addOption(private$..group)
            self$.addOption(private$..group1)
            self$.addOption(private$..count)
            self$.addOption(private$..prop)
            self$.addOption(private$..sum)
            self$.addOption(private$..disc)
            self$.addOption(private$..sum1)
            self$.addOption(private$..plot)
            self$.addOption(private$..angle)
            self$.addOption(private$..plot1)
            self$.addOption(private$..disi)
            self$.addOption(private$..plot2)
            self$.addOption(private$..total)
            self$.addOption(private$..scoring)
            self$.addOption(private$..plot3)
            self$.addOption(private$..width2)
            self$.addOption(private$..height2)
            self$.addOption(private$..width)
            self$.addOption(private$..height)
            self$.addOption(private$..width1)
            self$.addOption(private$..height1)
            self$.addOption(private$..width3)
            self$.addOption(private$..height3)
        }),
    active = list(
        vars = function() private$..vars$value,
        key = function() private$..key$value,
        num = function() private$..num$value,
        num1 = function() private$..num1$value,
        group = function() private$..group$value,
        group1 = function() private$..group1$value,
        count = function() private$..count$value,
        prop = function() private$..prop$value,
        sum = function() private$..sum$value,
        disc = function() private$..disc$value,
        sum1 = function() private$..sum1$value,
        plot = function() private$..plot$value,
        angle = function() private$..angle$value,
        plot1 = function() private$..plot1$value,
        disi = function() private$..disi$value,
        plot2 = function() private$..plot2$value,
        total = function() private$..total$value,
        scoring = function() private$..scoring$value,
        plot3 = function() private$..plot3$value,
        width2 = function() private$..width2$value,
        height2 = function() private$..height2$value,
        width = function() private$..width$value,
        height = function() private$..height$value,
        width1 = function() private$..width1$value,
        height1 = function() private$..height1$value,
        width3 = function() private$..width3$value,
        height3 = function() private$..height3$value),
    private = list(
        ..vars = NA,
        ..key = NA,
        ..num = NA,
        ..num1 = NA,
        ..group = NA,
        ..group1 = NA,
        ..count = NA,
        ..prop = NA,
        ..sum = NA,
        ..disc = NA,
        ..sum1 = NA,
        ..plot = NA,
        ..angle = NA,
        ..plot1 = NA,
        ..disi = NA,
        ..plot2 = NA,
        ..total = NA,
        ..scoring = NA,
        ..plot3 = NA,
        ..width2 = NA,
        ..height2 = NA,
        ..width = NA,
        ..height = NA,
        ..width1 = NA,
        ..height1 = NA,
        ..width3 = NA,
        ..height3 = NA)
)

itemResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "itemResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        text = function() private$.items[["text"]],
        count = function() private$.items[["count"]],
        prop = function() private$.items[["prop"]],
        sum = function() private$.items[["sum"]],
        disc = function() private$.items[["disc"]],
        sum1 = function() private$.items[["sum1"]],
        plot2 = function() private$.items[["plot2"]],
        plot = function() private$.items[["plot"]],
        plot1 = function() private$.items[["plot1"]],
        total = function() private$.items[["total"]],
        scoring = function() private$.items[["scoring"]],
        plot3 = function() private$.items[["plot3"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Distractor analysis",
                refs="snowIRT")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title=""))
            self$add(jmvcore::Array$new(
                options=options,
                name="count",
                title="Counts of respondents",
                visible="(count)",
                refs="CTT",
                items="(vars)",
                template=jmvcore::Table$new(
                    options=options,
                    title="Item $key",
                    rows=0,
                    clearWith=list(
                        "vars",
                        "key"),
                    columns=list(
                        list(
                            `name`="name", 
                            `title`="", 
                            `type`="text", 
                            `content`="($key)"),
                        list(
                            `name`="lower", 
                            `title`="lower", 
                            `type`="integer"),
                        list(
                            `name`="middle", 
                            `title`="middle", 
                            `type`="integer"),
                        list(
                            `name`="upper", 
                            `title`="upper", 
                            `type`="integer")))))
            self$add(jmvcore::Array$new(
                options=options,
                name="prop",
                title="Proportions of respondents",
                visible="(prop)",
                refs="CTT",
                items="(vars)",
                template=jmvcore::Table$new(
                    options=options,
                    title="Item $key",
                    rows=0,
                    clearWith=list(
                        "vars",
                        "key"),
                    columns=list(
                        list(
                            `name`="name", 
                            `title`="", 
                            `type`="text", 
                            `content`="($key)"),
                        list(
                            `name`="lower", 
                            `title`="Lower", 
                            `type`="number"),
                        list(
                            `name`="middle", 
                            `title`="Middle", 
                            `type`="number"),
                        list(
                            `name`="upper", 
                            `title`="Upper", 
                            `type`="number")))))
            self$add(jmvcore::Array$new(
                options=options,
                name="sum",
                title="Item summary",
                visible="(sum)",
                refs="CTT",
                items="(vars)",
                template=jmvcore::Table$new(
                    options=options,
                    title="Item $key",
                    rows=0,
                    clearWith=list(
                        "vars",
                        "key"),
                    columns=list(
                        list(
                            `name`="correct", 
                            `title`="Correct", 
                            `type`="text", 
                            `content`="($key)"),
                        list(
                            `name`="key", 
                            `title`="Response", 
                            `type`="text", 
                            `content`="($key)"),
                        list(
                            `name`="n", 
                            `title`="Frequency", 
                            `type`="integer"),
                        list(
                            `name`="rspP", 
                            `title`="Proportion", 
                            `type`="number")))))
            self$add(jmvcore::Table$new(
                options=options,
                name="disc",
                title="Item difficulty and discrimination index",
                visible="(disc)",
                rows="(vars)",
                clearWith=list(
                    "vars",
                    "key"),
                refs="ShinyItemAnalysis",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="Item", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="dif", 
                        `title`="Difficulty"),
                    list(
                        `name`="ULI", 
                        `title`="ULI"),
                    list(
                        `name`="RIT", 
                        `title`="RIT"),
                    list(
                        `name`="RIR", 
                        `title`="RIR"))))
            self$add(jmvcore::Array$new(
                options=options,
                name="sum1",
                title="Total summary",
                visible="(sum1)",
                refs="CTT",
                items="(vars)",
                template=jmvcore::Table$new(
                    options=options,
                    title="Item $key",
                    clearWith=list(
                        "vars",
                        "key",
                        "group1"),
                    columns=list(
                        list(
                            `name`="name", 
                            `title`="", 
                            `type`="text", 
                            `content`="($key)")))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot2",
                title="Histogram of total score",
                requiresData=TRUE,
                visible="(plot2)",
                renderFun=".plot2",
                refs="ShinyItemAnalysis",
                clearWith=list(
                    "vars",
                    "key",
                    "width2",
                    "height2")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Distractor plot",
                requiresData=TRUE,
                visible="(plot)",
                renderFun=".plot",
                refs="ShinyItemAnalysis",
                clearWith=list(
                    "vars",
                    "num",
                    "group",
                    "key",
                    "width",
                    "height")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Discrimination plot",
                visible="(plot1)",
                renderFun=".plot1",
                refs="ShinyItemAnalysis",
                clearWith=list(
                    "vars",
                    "disi",
                    "angle",
                    "key",
                    "width1",
                    "height1")))
            self$add(jmvcore::Output$new(
                options=options,
                name="total",
                title="Total",
                varTitle="Total",
                measureType="continuous",
                clearWith=list(
                    "vars",
                    "key")))
            self$add(jmvcore::Output$new(
                options=options,
                name="scoring",
                title="Scoring",
                clearWith=list(
                    "vars",
                    "key")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot3",
                title="Empirical Item Characteristic Curve",
                requiresData=TRUE,
                visible="(plot3)",
                renderFun=".plot3",
                refs="CTT",
                clearWith=list(
                    "vars",
                    "num1",
                    "key",
                    "width3",
                    "height3")))}))

itemBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "itemBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowIRT",
                name = "item",
                version = c(1,0,0),
                options = options,
                results = itemResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Distractor analysis
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param key .
#' @param num .
#' @param num1 .
#' @param group .
#' @param group1 .
#' @param count .
#' @param prop .
#' @param sum .
#' @param disc .
#' @param sum1 .
#' @param plot .
#' @param angle a number from 0 to 90 defining the angle of the x-axis labels,
#'   where 0 degrees represents completely horizontal labels.
#' @param plot1 .
#' @param disi .
#' @param plot2 .
#' @param plot3 .
#' @param width2 .
#' @param height2 .
#' @param width .
#' @param height .
#' @param width1 .
#' @param height1 .
#' @param width3 .
#' @param height3 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$count} \tab \tab \tab \tab \tab an array of tables \cr
#'   \code{results$prop} \tab \tab \tab \tab \tab an array of tables \cr
#'   \code{results$sum} \tab \tab \tab \tab \tab an array of tables \cr
#'   \code{results$disc} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$sum1} \tab \tab \tab \tab \tab an array of tables \cr
#'   \code{results$plot2} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$total} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$scoring} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$plot3} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$disc$asDF}
#'
#' \code{as.data.frame(results$disc)}
#'
#' @export
item <- function(
    data,
    vars,
    key = "D,C,A,D,D,A,D,B,D,A,A,D,C,C,B,C,D,A,A,B",
    num = 1,
    num1 = 1,
    group = 3,
    group1 = 3,
    count = TRUE,
    prop = FALSE,
    sum = FALSE,
    disc = FALSE,
    sum1 = FALSE,
    plot = FALSE,
    angle = 0,
    plot1 = FALSE,
    disi,
    plot2 = FALSE,
    plot3 = FALSE,
    width2 = 500,
    height2 = 500,
    width = 500,
    height = 500,
    width1 = 500,
    height1 = 500,
    width3 = 500,
    height3 = 500) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("item requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))

    for (v in vars) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- itemOptions$new(
        vars = vars,
        key = key,
        num = num,
        num1 = num1,
        group = group,
        group1 = group1,
        count = count,
        prop = prop,
        sum = sum,
        disc = disc,
        sum1 = sum1,
        plot = plot,
        angle = angle,
        plot1 = plot1,
        disi = disi,
        plot2 = plot2,
        plot3 = plot3,
        width2 = width2,
        height2 = height2,
        width = width,
        height = height,
        width1 = width1,
        height1 = height1,
        width3 = width3,
        height3 = height3)

    analysis <- itemClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

