
# This file is automatically generated, you probably don't want to edit this

logitOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "logitOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            group = NULL,
            model = "adjacent",
            type = "both",
            match = "zscore",
            padjust = "none",
            dif = TRUE, ...) {

            super$initialize(
                package="snowIRT",
                name="logit",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..model <- jmvcore::OptionList$new(
                "model",
                model,
                options=list(
                    "adjacent",
                    "cumulative"),
                default="adjacent")
            private$..type <- jmvcore::OptionList$new(
                "type",
                type,
                options=list(
                    "both",
                    "udif",
                    "nudif"),
                default="both")
            private$..match <- jmvcore::OptionList$new(
                "match",
                match,
                options=list(
                    "zscore",
                    "score"),
                default="zscore")
            private$..padjust <- jmvcore::OptionList$new(
                "padjust",
                padjust,
                options=list(
                    "none",
                    "holm",
                    "hochberg",
                    "hommel",
                    "bonferroni",
                    "BH",
                    "BY",
                    "fdr"),
                default="none")
            private$..dif <- jmvcore::OptionBool$new(
                "dif",
                dif,
                default=TRUE)

            self$.addOption(private$..vars)
            self$.addOption(private$..group)
            self$.addOption(private$..model)
            self$.addOption(private$..type)
            self$.addOption(private$..match)
            self$.addOption(private$..padjust)
            self$.addOption(private$..dif)
        }),
    active = list(
        vars = function() private$..vars$value,
        group = function() private$..group$value,
        model = function() private$..model$value,
        type = function() private$..type$value,
        match = function() private$..match$value,
        padjust = function() private$..padjust$value,
        dif = function() private$..dif$value),
    private = list(
        ..vars = NA,
        ..group = NA,
        ..model = NA,
        ..type = NA,
        ..match = NA,
        ..padjust = NA,
        ..dif = NA)
)

logitResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "logitResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        dif = function() private$.items[["dif"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="DIF with cumulative logit")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="DIF with cumulative logit"))
            self$add(jmvcore::Table$new(
                options=options,
                name="dif",
                title="DIF detection among ordinal data",
                visible="(dif)",
                rows="(vars)",
                clearWith=list(
                    "vars"),
                refs="ShinyItemAnalysis",
                columns=list(
                    list(
                        `name`="name", 
                        `title`="Item", 
                        `type`="text", 
                        `content`="($key)"))))}))

logitBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "logitBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowIRT",
                name = "logit",
                version = c(1,0,0),
                options = options,
                results = logitResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' DIF with cumulative logit
#'
#' 
#' @param data The data as a data frame.
#' @param vars .
#' @param group A string naming the grouping variable from \code{data}
#' @param model .
#' @param type .
#' @param match .
#' @param padjust .
#' @param dif .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$dif} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$dif$asDF}
#'
#' \code{as.data.frame(results$dif)}
#'
#' @export
logit <- function(
    data,
    vars,
    group,
    model = "adjacent",
    type = "both",
    match = "zscore",
    padjust = "none",
    dif = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("logit requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(group), group, NULL))


    options <- logitOptions$new(
        vars = vars,
        group = group,
        model = model,
        type = type,
        match = match,
        padjust = padjust,
        dif = dif)

    analysis <- logitClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

